import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { resolveLanguage, EXT_STRINGS } from '../i18n';

export async function saveAuthorAliases(
  workspacePath: string,
  target: 'settings' | 'mailmap',
  aliases: Record<string, string[]>,
  onRescan?: () => Promise<void>
): Promise<void> {
  const lang = resolveLanguage();
  const t = EXT_STRINGS[lang];

  try {
    const totalGroups = Object.keys(aliases).length;

    if (target === 'settings') {
      const config = vscode.workspace.getConfiguration('auspex');
      await config.update('authorAliases', aliases, vscode.ConfigurationTarget.Workspace);
    } else {
      // Target is .mailmap
      const mailmapFile = path.join(workspacePath, '.mailmap');
      const lines: string[] = ['# Generated by Auspex Author Consolidation'];

      for (const [canonical, aliasList] of Object.entries(aliases)) {
        const cleanCanonical = (canonical || '').trim();
        if (!cleanCanonical) continue;

        for (const rawAlias of aliasList) {
          const cleanAlias = (rawAlias || '').trim();
          if (!cleanAlias) continue;

          if (cleanAlias.includes('<') && cleanAlias.includes('>')) {
            lines.push(`${cleanCanonical} ${cleanAlias}`);
          } else if (cleanAlias.includes('@')) {
            lines.push(`${cleanCanonical} <${cleanAlias}>`);
          } else {
            // Mapping alias name to canonical name
            lines.push(`${cleanCanonical} <${cleanAlias}> ${cleanAlias} <${cleanAlias}>`);
          }
        }
      }

      await fs.promises.writeFile(mailmapFile, lines.join('\n') + '\n', 'utf-8');
    }

    vscode.window.showInformationMessage(t.authorAliasesSaved(totalGroups));

    if (onRescan) {
      await onRescan();
    }
  } catch (err: any) {
    console.error('[Auspex] Error saving author aliases:', err);
    vscode.window.showErrorMessage(t.authorAliasesSaveError(err?.message || String(err)));
  }
}
